version: '3'
services:
  postgres:
    image: postgres
    # network_mode: 'host'
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=harity
    ports:
      - '5432:5432'
    expose:
      - '5432'
    # volumes:
    #   - ~/postgres_data:/var/lib/postgresql/data
